steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$finance-expenses-app/expense-tracker-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$finance-expenses-app/expense-tracker-backend']

images:
  - 'us-central1-docker.pkg.dev/$finance-expenses-app/expense-tracker-backend'

options:
  logging: CLOUD_LOGGING_ONLY